# Generated by Django 4.0.5 on 2022-06-15 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Job', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='applied_developers',
            field=models.ManyToManyField(blank=True, related_name='applied_developers', to=settings.AUTH_USER_MODEL, verbose_name='Applied developers'),
        ),
        migrations.AddField(
            model_name='job',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Job_Owner', to=settings.AUTH_USER_MODEL, verbose_name='Job_Owner'),
        ),
        migrations.AddField(
            model_name='job',
            name='developer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Accepted_Developer', to=settings.AUTH_USER_MODEL, verbose_name='Accepted_Developer'),
        ),
    ]
