# Generated by Django 4.0.5 on 2022-06-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image_banner',
            field=models.ImageField(default='mahy.png', upload_to=''),
        ),
    ]
