# Generated by Django 4.0.4 on 2022-06-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0002_job_image_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Creation_time',
            field=models.DateField(auto_now_add=True, verbose_name='Creation Time'),
        ),
    ]
