# Generated by Django 4.0.4 on 2022-06-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0003_alter_job_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image_banner',
            field=models.ImageField(default='lab4_odoo.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Inprogress', 'Inprogress'), ('Finished', 'Finished')], default='Open', max_length=100),
        ),
    ]
